name: Box Doc Checker

on: [pull_request]

jobs:
  check-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install box-sdk-gen
      - name: Run Box Check
        env:
          BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          BOX_ENTERPRISE_ID: ${{ secrets.BOX_ENTERPRISE_ID }}
        run: python scripts/check_docs.py
